### ISSUE TITLE
panic: No suitable endpoint could be found in the service catalog

### ISSUE THREAD

**Issue by parveenb1** [carlpett/openstack-ceilometer_exporter#1]
I have build the exporter and when running with command openstack-ceilometer_exporter getting error

**Comment by carlpett** [comment]
@parveenb1 Sorry about the late response - Github had unsubscribed me from notifications in my own repos. 
Regarding the error, this sounds like your Openstack setup does not have the Ceilometer service?

**Comment by carlpett** [comment]
Closing due to lack of response. Feel free to reopen if there is new information.
